### ISSUE TITLE
svc_release_it() causes xp_refs to go negative when svc_dg_reply() fails in SVCAUTH_WRAP

### ISSUE THREAD

**Issue by michaelzeis** [nfs-ganesha/ntirpc#129]
While trying mount an NFS export using UDP only, I am hitting a problem where a svc_dg_reply of the UDP request fails in the SVCAUTH_WRAP() call.   

This results in svc_release_it() being called twice, once from svc_destroy_it() and then again from free_nfs_request, which causes xp_refs to go to -1, and then the worker-pool goes into an infinite dispatch loop trying to release the xprt.

Here's the log trace I am referring to:

```
2018-04-06T19:51:50.728177+0000 6667[svc_15] rpc :TIRPC :F_DBG :svc_dg_reply: 0x7f97d80008c0 fd 25 SVCAUTH_WRAP failed (will set dead)
2018-04-06T19:51:50.728188+0000 6667[svc_15] rpc :TIRPC :F_DBG :svc_destroy_it() 0x7f97d80008c0 fd 25 xp_refs 1 af 10 port 840 @ nfs_rpc_process_request:1404
2018-04-06T19:51:50.728196+0000 6667[svc_15] rpc :TIRPC :F_DBG :svc_release_it() 0x7f97d80008c0 fd 25 xp_refs 0 af 10 port 840 @ nfs_rpc_process_request:1404
2018-04-06T19:51:50.728207+0000 6667[svc_15] rpc :TIRPC :F_DBG :svc_dg_destroy_it() 0x7f97d80008c0 fd 25 xp_refs 0 should actually destroy things @ nfs_rpc_process_request:1404
2018-04-06T19:51:50.728885+0000 6667[svc_15] rpc :TIRPC :F_DBG :svc_release_it() 0x7f97d80008c0 fd 25 xp_refs -1 af 10 port 840 @ free_nfs_request:1281
```

I wonder if a fix in svc_release_it() could be done to move the atomic_dec_uint32_t(&xprt->xp_refs) call after the check of SVC_XPRT_FLAG_RELEASING would fix it, like this:

```
static inline void svc_release_it(SVCXPRT *xprt, u_int flags,
                  const char *tag, const int line)
{
    uint32_t refs;
    uint16_t xp_flags;

    /* enforce once-only semantic, trace others */
    xp_flags = atomic_postset_uint16_t_bits(&xprt->xp_flags,
                        SVC_XPRT_FLAG_RELEASING);

    if (xp_flags & SVC_XPRT_FLAG_RELEASING) {
        XPRT_TRACE(xprt, "WARNING! already destroying!", tag, line);
        return;
    }
    refs = atomic_dec_uint32_t(&xprt->xp_refs);
```

I don't know yet why the SVCAUTH_WRAP() is failing and preventing the UDP reply from being sent, which is what exposed this issue in the first place, but once this occurs the worker-pool threads get stuck in a dispatch loop trying to release the xprt.

**Comment by dang** [comment]
This sounds familiar, like maybe we fixed it.  What version is this?

**Comment by michaelzeis** [comment]
This was 1.7.0.   If I look at latest 'next' of svc_release_it() there is still a decrement of xp_refs before a check of xp_flags.  So it seems the issue is still there?

If was able to hit this when I added 'Transports = UDP;' to the ganesha export definition and tried to mount it from a Linux 7.4. CentOS client using options: '-o vers=3,proto=udp'.

**Comment by was4** [comment]
On 4/6/18 6:50 PM, Michael Zeis wrote:
> While trying mount an NFS export using UDP only, I am hitting a problem where a svc_dg_reply of the UDP request fails in the SVCAUTH_WRAP() call.
> 
UDP isn't well tested.  Usually only good paths are tested during CI.

> This results in svc_release_it() being called twice, once from svc_destroy_it() and then again from free_nfs_request, which causes xp_refs to go to -1, and then the worker-pool goes into an infinite dispatch loop trying to release the xprt.
> 
We've seen similar issues in the past.

I'd made svc_release_it() and svc_destroy_it() several years ago.  So a
logic change here would need a lot of deep examination.

But this free_nfs_request() UDP code path is new in Ganesha V2.6, in an
attempt to make UDP as parallel as TCP.  In all previous versions, UDP
had a single shared input and output buffer (left over from tirpc).

DanG and I were supposed to meet yesterday, but he got sick.

Hold on, we'll try later in the week.

> I don't know yet why the SVCAUTH_WRAP() is failing and preventing the UDP reply from being sent, which is what exposed this issue in the first place, but once this occurs the worker-pool threads get stuck in a dispatch loop trying to release the xprt.
> 
Yeah, please don't fix it yet.  Nice to have an error path to test. ;)

**Comment by was4** [comment]
On 4/6/18 6:50 PM, Michael Zeis wrote:
> 2018-04-06T19:51:50.728177+0000 6667[svc_15] rpc :TIRPC :F_DBG :svc_dg_reply: 0x7f97d80008c0 fd 25 SVCAUTH_WRAP failed (will set dead)

> 2018-04-06T19:51:50.728188+0000 6667[svc_15] rpc :TIRPC :F_DBG :svc_destroy_it() 0x7f97d80008c0 fd 25 xp_refs 1 af 10 port 840 @ nfs_rpc_process_request:1404

At this point, xp_refs should be minimum 2: from the nfs_request,
and from the svc_rqst/svc_xprt list.  UDP unlike TCP has some odder
counting, with a note in the svc_dg_recv() code.

This is new code, and it could certainly be wrong for error paths.

Need more log.  Please send every line with 0x7f97d80008c0 (or its
equivalent in the next run).  The fd is meaningless here, as it is
the same for all UDP connections.

I've got no idea how you have a port 840....

Heck, I'm really surprised at the af 10: X.121 (X.25, Frame Relay).

Could be some fields aren't being setup properly.

**Comment by was4** [comment]
I've been thinking about SVC_DESTROY().  This was for TCP, and in
the past had no meaning for UDP.  UDP SVCXPRT was never destroyed,
as there was only one.

With the addition of async UDP client calls, per port UDP SVCXPRT
will stay around until all the calls complete or timeout.  So
SVC_DESTROY() is having an effect, as there is something there.

I'm thinking that SVC_DESTROY() should only set the DESTROYING
flag without releasing, then TCP should release at the end of its
code path only when DESTROYING is set.

This would need a complete audit of every use of DESTROY.

Discuss.

**Comment by was4** [comment]
On 4/11/18 1:41 AM, William Allen Simpson wrote:
> On 4/6/18 6:50 PM, Michael Zeis wrote:
> Hold on, we'll try later in the week.
> 
This went in 2.7-dev.8, could you test and make sure it fixes the error case?


>> I don't know yet why the SVCAUTH_WRAP() is failing and preventing the UDP reply from being sent, which is what exposed this issue in the first place, but once this occurs the worker-pool threads get stuck in a dispatch loop trying to release the xprt.
>>
> Yeah, please don't fix it yet.  Nice to have an error path to test. ;)

Assuming this issue is fixed, could you please open a new issue for UDP SVCAUTH_WRAP()?

**Comment by michaelzeis** [comment]
OK, I'll try out the fix and then open up a new issue to track the remaining UDP SVCAUTH _WRAP problem.

**Comment by michaelzeis** [comment]
Your changes to svc_dg_recv() in svc_dg.c to fix the refcnt problem worked for me.  I could mount an export using UDP successfully now.

Surprisingly,  I no longer get the UDP SVCAUTH_WRAP problem anymore either using this fix in combination with the ntohl fixes you made earlier.   I was able to successfully use the UDP export without errors.
